import './globals.css';
import { SearchProvider, WikiProvider } from './providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <WikiProvider>
          <SearchProvider>{children}</SearchProvider>
        </WikiProvider>
      </body>
    </html>
  );
}
